FROM alpine:latest

RUN apk add --no-cache bash curl libstdc++ libgcc && \
  curl -fsSL https://bun.sh/install | bash

ENV BUN_INSTALL="/root/.bun"
ENV PATH="$BUN_INSTALL/bin:$PATH"

WORKDIR /usr/src/app

COPY package.json bun.lock ./

RUN bun install

COPY . .
EXPOSE 3000

CMD ["bun", "run", "start"]
